apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-gke
  labels:
    app: url-shortener-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-gke
  template:
    metadata:
      labels:
        app: url-shortener-gke
    spec:
      containers:
        - name: url-shortener-gke
          image: us-central1-docker.pkg.dev/doaas-project/doaas/url-shortener-gke:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
